# Chisel 生成 verilog 配置
CHISEL_VERILOG_CONFIG=ICACHE_SIZE_BITS=2
CHISEL_VERILOG_CONFIG+=ICACHE_BLOCK_BITS=0
CHISEL_VERILOG_CONFIG+=ICACHE_ENABLE_BURST=false
CHISEL_VERILOG_CONFIG+=ENABLE_SOC=false
IVERILOG_MAIN_FILE := $(NPC_HOME)/vsrc/iverilog_main.v

verilog_iverlog: 
	@echo CHISEL_VERILOG_CONFIG $(CHISEL_VERILOG_CONFIG) 
	$(MAKE) -C $(NPC_CHISEL_HOME) $(CHISEL_VERILOG_CONFIG) verilog_iverlog

iverilog-build: $(SVSOURCES) $(IVERILOG_MAIN_FILE)
	mkdir -p $(BUILD_DIR)/iverilog
	iverilog $(VINCLUDES) -o $(BUILD_DIR)/iverilog/main.vvp  $(IVERILOG_MAIN_FILE) $(SVSOURCES) -g2012 

