# Chisel专用配置
BUILD_DIR = $(BUILD_DIR_BASE)/npc-chisel
VERILATOR_FLAGS = $(VERILATOR_BASE_FLAGS) --Mdir $(BUILD_DIR)
TOP_NAME = ysyxSoCFull
NAME = V$(TOP_NAME)

ICACHE_SIZE_BITS=3
ICACHE_BLOCK_BITS=1
ICACHE_ENABLE_BURST=true
CHISEL_SOC_CONFIG=ICACHE_SIZE_BITS=$(ICACHE_SIZE_BITS) ICACHE_BLOCK_BITS=$(ICACHE_BLOCK_BITS) ICACHE_ENABLE_BURST=$(ICACHE_ENABLE_BURST)
# SV源文件
ifdef CONFIG_SOC
	SVSOURCES = $(wildcard $(NPC_HOME)/build/*.v $(NPC_HOME)/build/*.sv)
else
	SVSOURCES = $(wildcard $(NPC_HOME)/svsrc_no_soc/*.v $(NPC_HOME)/svsrc_no_soc/*.sv)
endif
BINARY = $(BUILD_DIR)/$(NAME)
NPC_EXEC = $(BINARY) $(ARGS) $(IMG)
NPC_PERF = $(BINARY) $(PERF_ARGS) $(IMG)


VSINC_PATH := $(SOC_HOME)/perip/uart16550/rtl
VSINC_PATH += $(SOC_HOME)/perip/spi/rtl
VINCLUDES = $(addprefix -I, $(VSINC_PATH))
VERILATOR_BASE_FLAGS += $(VINCLUDES)
VERILATOR_BASE_FLAGS += --top-module $(TOP_NAME)


build:$(SVSOURCES) $(SOURCES) $(NVBOARD_ARCHIVE) 
	mkdir -p $(BUILD_DIR)
	verilator -Wno-DECLFILENAME  $(VERILATOR_FLAGS) $(SOURCES) $(SVSOURCES)  --trace-fst --autoflush

lint:$(SVSOURCES) $(SOURCES) $(NVBOARD_ARCHIVE) 
	verilator --lint-only -Wall -Wno-DECLFILENAME  $(VERILATOR_FLAGS) $(SOURCES) $(SVSOURCES) 

verilog: 
	$(MAKE) -C $(NPC_CHISEL_HOME) $(CHISEL_SOC_CONFIG) verilog
