# Chisel专用配置
BUILD_DIR = $(BUILD_DIR_BASE)/npc-chisel
VERILATOR_FLAGS = $(VERILATOR_BASE_FLAGS) --Mdir $(BUILD_DIR)
TOP_NAME = ysyxSoCFull
NAME = V$(TOP_NAME)

# Chisel 生成 verilog 配置
CHISEL_VERILOG_CONFIG=ICACHE_SIZE_BITS=2
CHISEL_VERILOG_CONFIG+=ICACHE_BLOCK_BITS=0
CHISEL_VERILOG_CONFIG+=ICACHE_ENABLE_BURST=false


# SV源文件
SVSOURCES = $(wildcard $(NPC_HOME)/svsrc_no_soc/*.v $(NPC_HOME)/svsrc_no_soc/*.sv)

BINARY = $(BUILD_DIR)/$(NAME)
NPC_EXEC = $(BINARY) $(ARGS) $(IMG)
NPC_PERF = $(BINARY) $(PERF_ARGS) $(IMG)


VSINC_PATH := $(SOC_HOME)/perip/uart16550/rtl
VSINC_PATH += $(SOC_HOME)/perip/spi/rtl
VINCLUDES = $(addprefix -I, $(VSINC_PATH))
VERILATOR_BASE_FLAGS += $(VINCLUDES)
VERILATOR_BASE_FLAGS += --top-module $(TOP_NAME)

verilog: 
	$(MAKE) -C $(NPC_CHISEL_HOME) $(CHISEL_VERILOG_CONFIG) verilog_npc

build: verilog $(SVSOURCES) $(SOURCES) $(NVBOARD_ARCHIVE) 
	mkdir -p $(BUILD_DIR)
	verilator -Wno-DECLFILENAME  $(VERILATOR_FLAGS) $(SOURCES) $(SVSOURCES)  --trace-fst --autoflush

lint:$(SVSOURCES) $(SOURCES) $(NVBOARD_ARCHIVE) 
	verilator --lint-only -Wall -Wno-DECLFILENAME  $(VERILATOR_FLAGS) $(SOURCES) $(SVSOURCES) 

