# Chisel 生成 verilog 配置
ifdef CONFIG_TRACE
	CHISEL_VERILOG_GALOIS_NPC_CONFIG+=NPC_ENABLE_DEBUG=true
else 
	CHISEL_VERILOG_GALOIS_NPC_CONFIG+=NPC_ENABLE_DEBUG=false
endif
CHISEL_VERILOG_GALOIS_NPC_CONFIG+=NPC_ENABLE_DEBUG=true
CHISEL_VERILOG_CONFIG+=ENABLE_SOC=false

verilog-galois-npc: 
	@echo CHISEL_VERILOG_GALOIS_NPC_CONFIG $(CHISEL_VERILOG_GALOIS_NPC_CONFIG)
	$(MAKE) -C ../npc-chisel $(CHISEL_VERILOG_GALOIS_NPC_CONFIG) verilog-galois

